//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flasher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flasher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::[Bat To Exe Converter]
        ///::
        ///::YAwzoRdxOk+EWAnk
        ///::fBw5plQjdG8=
        ///::YAwzuBVtJxjWCl3EqQJgSA==
        ///::ZR4luwNxJguZRRnk
        ///::Yhs/ulQjdF+5
        ///::cxAkpRVqdFKZSDk=
        ///::cBs/ulQjdF+5
        ///::ZR41oxFsdFKZSDk=
        ///::eBoioBt6dFKZSDk=
        ///::cRo6pxp7LAbNWATEpCI=
        ///::egkzugNsPRvcWATEpCI=
        ///::dAsiuh18IRvcCxnZtBJQ
        ///::cRYluBh/LU+EWAnk
        ///::YxY4rhs+aU+JeA==
        ///::cxY6rQJ7JhzQF1fEqQJQ
        ///::ZQ05rAF9IBncCkqN+0xwdVs0
        ///::ZQ05rAF9IAHYFVzEqQJQ
        ///::eg0/rx1wNQPfEVWB+kM9LVsJDGQ=
        ///::fBEirQZwNQPfEVWB+kM9LVsJDGQ=
        ///::cRolqwZ3JBvQF1fEqQJQ
        ///::dhA7uBVwLU+EWDk=
        ///::YQ03rBFz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb {
            get {
                return ResourceManager.GetString("fb", resourceCulture);
            }
        }
    }
}
